### ISSUE TITLE
[Off topic - Encouragement] Keep up your good work

### ISSUE THREAD

**Issue by henrik-jensen** [jackpunt/markReadOnly#1]
Hey @jackpunt
I'm sorry I haven't been able to test your extension lately, though I've been keen on it. But a combination of a very tough case of severe back pains that needed medications and a windows system that just won't play ball with the vscode build have hindered me. When I'm up and running again I'll create a Virtual Linux machine, maybe a Linux partition or install it on a vanilla Windows 10 machine, so I can get something up and running, and give you some feed back on the mods and extension.
And sorry to use the issue channel for this, but I don't know how else to contact you through github.
Anyway, just close and delete this "issue" if you want.
And thank you for all you fantastic work.
--Henrik

**Comment by jackpunt** [comment]
Thanks for the info.
If you get things running, and have any feedback/suggestions, let me know.

**Comment by henrik-jensen** [comment]
Thanks.
Maan,- we have been wanting a solution for so long and, to me, it seems that your solution, because it's just small changes to the "kernel" that seems easily testable, could actually break through the protective "Microsoft VSCode dev. team firewall" and create a solution that they'll accept.
